apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
        - name: nginx
          image: singhjassi/nginx-reverse-proxy:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy-service
spec:
  type: NodePort
  selector:
    app: nginx-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

