apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      dnsPolicy: Default
      containers:
        - name: backend
          image: singhjassi/backendd:v1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
      app: backend-app
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31236
