name: Close PRs Without Linked Issues

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close_prs_without_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Close PRs Without Linked Issues
        run: node close-prs.js
